---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: plugins/docker
  settings:
    context: app
    dockerfile: app/Dockerfile
    force_tag: true
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/dq-acl-sftp-python
    tags:
    - ${DRONE_COMMIT_SHA}
    - ${DRONE_BUILD_NUMBER}
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - push

- name: anchore_scan
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  pull: always
  environment:
    #NOTE: Image name can't be a variable here!
    IMAGE_NAME: quay.io/ukhomeofficedigital/dq-acl-sftp-python:${DRONE_COMMIT_SHA}
    LOCAL_IMAGE: false
    SHOW_ALL_VULNERABILITIES: true
    TOLERATE: medium
    FAIL_ON_DETECTION: false
  when:
    event:
      - push

- name: deploy_to_dev
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
  - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
  - export ACL_SERVER=$$NOTPROD_ACL_SERVER
  - export ACL_USERNAME=$$NOTPROD_ACL_USERNAME
  - export ACL_PASSWORD=$$NOTPROD_ACL_PASSWORD
  - export ACL_LANDING_DIR=$$NOTPROD_ACL_LANDING_DIR
  - export S3_BUCKET_NAME=$$NOTPROD_S3_BUCKET_NAME
  - export S3_KEY_PREFIX=$$NOTPROD_S3_KEY_PREFIX
  - export S3_ACCESS_KEY_ID=$$NOTPROD_S3_ACCESS_KEY_ID
  - export S3_SECRET_ACCESS_KEY=$$NOTPROD_S3_SECRET_ACCESS_KEY
  - export ACL_RDS_HOST=$$NOTPROD_ACL_RDS_HOST
  - export ACL_RDS_DATABASE=$$NOTPROD_ACL_RDS_DATABASE
  - export ACL_RDS_USERNAME=$$NOTPROD_ACL_RDS_USERNAME
  - export ACL_RDS_PASSWORD=$$NOTPROD_ACL_RDS_PASSWORD
  - export ACL_RDS_TABLE=$$NOTPROD_ACL_RDS_TABLE
  - export SLACK_WEBHOOK=$$NOTPROD_SLACK_WEBHOOK
  - kd --delete --file kube/deployment.yml
  - kd -f kube/pvc.yml -f kube/secret.yml -f kube/deployment.yml
  environment:
    ACL_CPU_LIMIT: 2.5
    ACL_CPU_REQUEST: 2
    ACL_PVC_SIZE: 5Gi
    ACL_RAM_LIMIT: 4Gi
    ACL_RAM_REQUEST: 3Gi
    INSECURE_SKIP_TLS_VERIFY: true
    KUBE_NAMESPACE: dq-apps-notprod
    NOTPROD_ACL_LANDING_DIR:
      from_secret: NOTPROD_ACL_LANDING_DIR
    NOTPROD_ACL_PASSWORD:
      from_secret: NOTPROD_ACL_PASSWORD
    NOTPROD_ACL_RDS_DATABASE:
      from_secret: NOTPROD_ACL_RDS_DATABASE
    NOTPROD_ACL_RDS_HOST:
      from_secret: NOTPROD_ACL_RDS_HOST
    NOTPROD_ACL_RDS_PASSWORD:
      from_secret: NOTPROD_ACL_RDS_PASSWORD
    NOTPROD_ACL_RDS_TABLE:
      from_secret: NOTPROD_ACL_RDS_TABLE
    NOTPROD_ACL_RDS_USERNAME:
      from_secret: NOTPROD_ACL_RDS_USERNAME
    NOTPROD_ACL_SERVER:
      from_secret: NOTPROD_ACL_SERVER
    NOTPROD_ACL_USERNAME:
      from_secret: NOTPROD_ACL_USERNAME
    NOTPROD_KUBE_SERVER:
      from_secret: NOTPROD_KUBE_SERVER
    NOTPROD_KUBE_TOKEN:
      from_secret: NOTPROD_KUBE_TOKEN
    NOTPROD_S3_ACCESS_KEY_ID:
      from_secret: NOTPROD_S3_ACCESS_KEY_ID
    NOTPROD_S3_BUCKET_NAME:
      from_secret: NOTPROD_S3_BUCKET_NAME
    NOTPROD_S3_KEY_PREFIX:
      from_secret: NOTPROD_S3_KEY_PREFIX
    NOTPROD_S3_SECRET_ACCESS_KEY:
      from_secret: NOTPROD_S3_SECRET_ACCESS_KEY
    NOTPROD_SLACK_WEBHOOK:
      from_secret: NOTPROD_SLACK_WEBHOOK
  when:
    event:
    - push

- name: deploy_to_production
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
  - export KUBE_SERVER=$$PROD_KUBE_SERVER
  - export ACL_SERVER=$$PROD_ACL_SERVER
  - export ACL_USERNAME=$$PROD_ACL_USERNAME
  - export ACL_PASSWORD=$$PROD_ACL_PASSWORD
  - export ACL_LANDING_DIR=$$PROD_ACL_LANDING_DIR
  - export S3_BUCKET_NAME=$$PROD_S3_BUCKET_NAME
  - export S3_KEY_PREFIX=$$PROD_S3_KEY_PREFIX
  - export S3_ACCESS_KEY_ID=$$PROD_S3_ACCESS_KEY_ID
  - export S3_SECRET_ACCESS_KEY=$$PROD_S3_SECRET_ACCESS_KEY
  - export ACL_RDS_HOST=$$PROD_ACL_RDS_HOST
  - export ACL_RDS_DATABASE=$$PROD_ACL_RDS_DATABASE
  - export ACL_RDS_USERNAME=$$PROD_ACL_RDS_USERNAME
  - export ACL_RDS_PASSWORD=$$PROD_ACL_RDS_PASSWORD
  - export ACL_RDS_TABLE=$$PROD_ACL_RDS_TABLE
  - export SLACK_WEBHOOK=$$PROD_SLACK_WEBHOOK
  - kd --delete --file kube/deployment.yml
  - kd -f kube/pvc.yml -f kube/secret.yml -f kube/deployment.yml
  environment:
    ACL_CPU_LIMIT: 2.5
    ACL_CPU_REQUEST: 2
    ACL_PVC_SIZE: 5Gi
    ACL_RAM_LIMIT: 4Gi
    ACL_RAM_REQUEST: 3Gi
    INSECURE_SKIP_TLS_VERIFY: true
    KUBE_NAMESPACE: dq-apps
    PROD_ACL_LANDING_DIR:
      from_secret: PROD_ACL_LANDING_DIR
    PROD_ACL_PASSWORD:
      from_secret: PROD_ACL_PASSWORD
    PROD_ACL_RDS_DATABASE:
      from_secret: PROD_ACL_RDS_DATABASE
    PROD_ACL_RDS_HOST:
      from_secret: PROD_ACL_RDS_HOST
    PROD_ACL_RDS_PASSWORD:
      from_secret: PROD_ACL_RDS_PASSWORD
    PROD_ACL_RDS_TABLE:
      from_secret: PROD_ACL_RDS_TABLE
    PROD_ACL_RDS_USERNAME:
      from_secret: PROD_ACL_RDS_USERNAME
    PROD_ACL_SERVER:
      from_secret: PROD_ACL_SERVER
    PROD_ACL_USERNAME:
      from_secret: PROD_ACL_USERNAME
    PROD_KUBE_SERVER:
      from_secret: PROD_KUBE_SERVER
    PROD_KUBE_TOKEN:
      from_secret: PROD_KUBE_TOKEN
    PROD_S3_ACCESS_KEY_ID:
      from_secret: PROD_S3_ACCESS_KEY_ID
    PROD_S3_BUCKET_NAME:
      from_secret: PROD_S3_BUCKET_NAME
    PROD_S3_KEY_PREFIX:
      from_secret: PROD_S3_KEY_PREFIX
    PROD_S3_SECRET_ACCESS_KEY:
      from_secret: PROD_S3_SECRET_ACCESS_KEY
    PROD_SLACK_WEBHOOK:
      from_secret: PROD_SLACK_WEBHOOK
  when:
    branch:
    - master
    event:
    - promote
    target:
    - production

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  - name: anchore-submission-server
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
    pull: always
    commands:
      - /run.sh server
