kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: acl-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2-encrypted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .PVC_SIZE }}
